[project]
name = "whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.0",
    "jiwer>=4.0.0",
    "openai-whisper>=20250625",
    "rich>=15.0.0",
    "soundfile>=0.14.0",
    "torch>=2.12.1",
    "torchcodec>=0.14.0",
    "tqdm>=4.68.3",
]
