#!/usr/bin/env bash
# One-time setup of KenLM on a Jetson AGX Orin (aarch64, Ubuntu/L4T).
#
# Produces two things:
#   1. The KenLM CLI tools (`lmplz`, `build_binary`) under
#      third_party/kenlm/build/bin - used by build_kenlm_models.sh to
#      *train* the n-gram models from text.
#   2. The `kenlm` Python package (query bindings only) installed into this
#      repo's uv-managed virtualenv (./.venv) - used by ngram_lm.py to
#      *score* candidates at eval time. Deliberately NOT installed with plain
#      `pip install` into the system Python: Debian/Ubuntu (incl. Jetson
#      L4T) marks the system Python as "externally managed" (PEP 668) and
#      will refuse it - and even if it didn't, `uv run` would still use the
#      project venv, not the system site-packages, so kenlm would be
#      invisible to eval_aishell_ngram_fusion.py anyway.
#
# kenlm's checked-in python/kenlm.cpp was pre-generated by an old Cython and
# uses private CPython C-API symbols (_PyGC_FINALIZED,
# _PyDict_SetItem_KnownHash, _PyGen_SetStopIterationValue, the pre-3.13
# _PyLong_AsByteArray signature) that Python 3.13 removed/changed, and
# setup.py always compiles that stale file rather than regenerating it - see
# https://github.com/kpu/kenlm/issues/471. This script works around it by
# regenerating python/kenlm.cpp from python/kenlm.pyx with a current Cython
# before installing, which is the fix the kenlm maintainers themselves give
# in that issue.
#
# Usage:
#   bash scripts/setup_kenlm_jetson.sh
#
# Safe to re-run; it skips steps that already succeeded.
set -euo pipefail

KENLM_MAX_ORDER="${KENLM_MAX_ORDER:-6}"  # must be >= the highest n-gram order you'll train (we use up to 5)
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THIRD_PARTY_DIR="${THIRD_PARTY_DIR:-${REPO_ROOT}/third_party}"
KENLM_SRC_DIR="${THIRD_PARTY_DIR}/kenlm"

echo "== Installing build dependencies (apt) =="
sudo apt-get update
sudo apt-get install -y \
    build-essential cmake \
    libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev \
    libeigen3-dev zlib1g-dev libbz2-dev liblzma-dev \
    ffmpeg  # not kenlm-related, but datasets' torchcodec audio backend needs it - see README

echo "== Cloning kenlm (for the lmplz/build_binary CLI tools) =="
mkdir -p "${THIRD_PARTY_DIR}"
if [ ! -d "${KENLM_SRC_DIR}" ]; then
    git clone https://github.com/kpu/kenlm.git "${KENLM_SRC_DIR}"
fi

echo "== Building kenlm CLI tools via cmake =="
mkdir -p "${KENLM_SRC_DIR}/build"
cd "${KENLM_SRC_DIR}/build"
cmake ..
make -j"$(nproc)"

echo "== CLI tools built: =="
echo "  lmplz:        ${KENLM_SRC_DIR}/build/bin/lmplz"
echo "  build_binary: ${KENLM_SRC_DIR}/build/bin/build_binary"

echo "== Ensuring the project virtualenv exists (uv sync) =="
( cd "${REPO_ROOT}" && uv sync )
VENV_PYTHON="${REPO_ROOT}/.venv/bin/python"
VENV_CYTHON="${REPO_ROOT}/.venv/bin/cython"

echo "== Installing Cython into the venv (needed to regenerate kenlm.cpp) =="
uv pip install --python "${VENV_PYTHON}" "cython>=3.0"

echo "== Regenerating python/kenlm.cpp from python/kenlm.pyx (fixes Python 3.13 compat - kpu/kenlm#471) =="
( cd "${KENLM_SRC_DIR}/python" && "${VENV_CYTHON}" -3 --cplus kenlm.pyx )

echo "== Installing the kenlm Python bindings into ${VENV_PYTHON} (MAX_ORDER=${KENLM_MAX_ORDER}) =="
MAX_ORDER="${KENLM_MAX_ORDER}" uv pip install --python "${VENV_PYTHON}" "${KENLM_SRC_DIR}"

echo "== Verifying the Python bindings import =="
"${VENV_PYTHON}" -c "import kenlm; print('kenlm python module OK, version file:', kenlm.__file__)"

cat <<EOF

Setup complete.

Next steps:
  export KENLM_BIN_DIR="${KENLM_SRC_DIR}/build/bin"
  uv run prepare_aishell_lm_corpus.py
  bash scripts/build_kenlm_models.sh
EOF
